---
title: "Project#1"
format: html
editor: visual
---

## Research Introduction

Question: Are certain exoplanet characteristics more likely to be observed by specific detection methods, i.e. will direct imaging find planets with higher masses relative to other discovery methods? Cluster will be the main method used to analyze the dataset.

Introduction: Exoplanet discovery is a relatively new field of science. As a result, the data that has been collected has some biases. For example, exoplanets with a long orbital period are not common discoveries since we haven't had the oppurtunity to see them make full orbits around their stars. With this limiting factor existing, different discovery methods have their own limiting factors. This project intends to discover those factors.

Hypothesis: Certain discovery methods will have an affect on what exoplanets they detect.

Dataset: The dataset being used in NASA's exoplanet archive which gives data on all known exoplanetary systems. The data was collected through various missions and telescopes. Variables such as discovery method, planet name, and planet mass are given.

## Running Code

data

```{r}
library(dplyr)
url <- "https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+*+from+pscomppars&format=csv"
planetdata <- read.csv(url)
glimpse(planetdata)
```

**README**

Dimensions: 67 Variables, 5869 observations

| Variable        | Description                         |
|-----------------|-------------------------------------|
| pl_name         | Planet name                         |
| hostname        | Host star name                      |
| discoverymethod | Method used to detect the exoplanet |
| pl_orbper       | Orbital period (days)               |
| pl_rade         | Planet radius (Earth radii)         |
| pl_bmasse       | Planet mass (Earth masses)          |
| st_teff         | Stellar effective temperature (K)   |
| st_mass         | Stellar mass (Solar masses)         |
| pl_orbsmax      | Semi-major axis (AU)                |
| disc_year       | Year of discovery                   |
